INSERT INTO MBTOOWNER.CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (MBTOOWNER.CUSTOMER_SEQ.nextval, 0, 'customer1', 100000);
INSERT INTO MBTOOWNER.CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (MBTOOWNER.CUSTOMER_SEQ.nextval, 0, 'customer2', 100000);
INSERT INTO MBTOOWNER.CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (MBTOOWNER.CUSTOMER_SEQ.nextval, 0, 'customer3', 100000);
INSERT INTO MBTOOWNER.CUSTOMER (ID, VERSION, NAME, CREDIT) VALUES (MBTOOWNER.CUSTOMER_SEQ.nextval, 0, 'customer4', 100000);
